version: "3.9"

services:
  backend:
    build: ./backend
    container_name: veritone-backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: veritone-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
